services:
  - type: web
    name: school-management-api
    env: node
    buildCommand: npm install
    startCommand: npm run start:render
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: USE_PG
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: school-management-db
          property: connectionString
      - key: DB_SSL_ENABLED
        value: true
          property: port
      - key: NODE_ENV
        value: production

databases:
  - name: school-management-db
    databaseName: school_management
    user: school_admin
